#!/usr/bin/env bash

# 🎯 QUICK START GUIDE - Ray Squad Production

echo "
╔═══════════════════════════════════════════════════════════╗
║         🌟 RAY SQUAD - PRODUCTION DEPLOYMENT 🌟          ║
╚═══════════════════════════════════════════════════════════╝
"

# Проверяем ОС
if [[ "$OSTYPE" == "msys" ]] || [[ "$OSTYPE" == "win32" ]]; then
    echo "⚠️  Вы на Windows. Используйте manual инструкции вместо этого скрипта."
    echo "📖 Откройте: DEPLOYMENT_GUIDE.md"
    exit 1
fi

# Меню выбора
echo "Выберите вариант развертывания:"
echo "1) Heroku (Рекомендуется для новичков)"
echo "2) PythonAnywhere"
echo "3) DigitalOcean"
echo "4) Мой собственный сервер"
echo "5) Выход"

read -p "Введите номер (1-5): " choice

case $choice in
    1)
        echo ""
        echo "🚀 Deployment на Heroku"
        echo "===================================="
        echo ""
        echo "ШАГ 1: Установите Heroku CLI"
        echo "  👉 https://devcenter.heroku.com/articles/heroku-cli"
        echo ""
        echo "ШАГ 2: Логинитесь"
        echo "  $ heroku login"
        echo ""
        echo "ШАГ 3: Создайте Git репозиторий (если его нет)"
        echo "  $ git init"
        echo "  $ git add ."
        echo "  $ git commit -m 'Initial commit'"
        echo ""
        echo "ШАГ 4: Создайте приложение на Heroku"
        echo "  $ heroku create your-app-name"
        echo ""
        echo "ШАГ 5: Установите переменные окружения"
        echo "  $ heroku config:set FLASK_ENV=production"
        echo "  $ heroku config:set SECRET_KEY=\$(python3 -c 'import secrets; print(secrets.token_hex(16))')"
        echo ""
        echo "ШАГ 6: Разверните"
        echo "  $ git push heroku main"
        echo ""
        echo "ШАГ 7: Примените миграции"
        echo "  $ heroku run python migrate_db.py"
        echo ""
        echo "✅ Ваше приложение доступно:"
        echo "  https://your-app-name.herokuapp.com"
        echo ""
        ;;
    2)
        echo ""
        echo "🐍 Deployment на PythonAnywhere"
        echo "===================================="
        echo ""
        echo "ШАГ 1: Создайте аккаунт"
        echo "  👉 https://www.pythonanywhere.com"
        echo ""
        echo "ШАГ 2: Загрузите исходный код"
        echo "  - Используйте файловый менеджер на PythonAnywhere"
        echo "  - Или используйте Bash консоль и git"
        echo ""
        echo "ШАГ 3: Создайте Web App"
        echo "  - Web > Add a new web app > Flask"
        echo ""
        echo "ШАГ 4: Установите зависимости"
        echo "  $ pip install -r requirements.txt"
        echo ""
        echo "ШАГ 5: Настройте WSGI файл"
        echo "  - Отредактируйте /var/www/your_username_pythonanywhere_com_wsgi.py"
        echo ""
        echo "ШАГ 6: Перезагрузите приложение"
        echo "  - Web > Reload your-domain.pythonanywhere.com"
        echo ""
        echo "✅ Ваше приложение доступно:"
        echo "  https://your-username.pythonanywhere.com"
        echo ""
        ;;
    3)
        echo ""
        echo "💧 Deployment на DigitalOcean"
        echo "===================================="
        echo ""
        echo "ШАГ 1: Создайте Droplet"
        echo "  - https://cloud.digitalocean.com"
        echo "  - Выберите Ubuntu 22.04"
        echo ""
        echo "ШАГ 2: SSH на сервер"
        echo "  $ ssh root@your-droplet-ip"
        echo ""
        echo "ШАГ 3: Установите Python и git"
        echo "  $ apt-get update && apt-get install -y python3-pip python3-venv git"
        echo ""
        echo "ШАГ 4: Клонируйте репозиторий"
        echo "  $ git clone your-github-repo.git app"
        echo "  $ cd app"
        echo ""
        echo "ШАГ 5: Создайте virtual environment"
        echo "  $ python3 -m venv venv"
        echo "  $ source venv/bin/activate"
        echo "  $ pip install -r requirements.txt"
        echo ""
        echo "ШАГ 6: Установите Nginx и Gunicorn"
        echo "  $ pip install gunicorn"
        echo "  $ apt-get install -y nginx"
        echo ""
        echo "ШАГ 7: Запустите приложение"
        echo "  $ gunicorn app:app --bind 127.0.0.1:5000 --workers 4"
        echo ""
        echo "ШАГ 8: Настройте Nginx (см. DEPLOYMENT_GUIDE.md)"
        echo ""
        echo "✅ Ваше приложение доступно:"
        echo "  https://your-droplet-ip.com"
        echo ""
        ;;
    4)
        echo ""
        echo "🖥️  Deployment на собственный сервер"
        echo "===================================="
        echo ""
        echo "Самостоятельные шаги:"
        echo ""
        echo "1. Установите Python 3.11+"
        echo "2. Клонируйте/загрузите код"
        echo "3. Создайте virtual environment"
        echo "4. Установите зависимости (pip install -r requirements.txt)"
        echo "5. Установите Gunicorn"
        echo "6. Запустите: gunicorn app:app --bind 0.0.0.0:5000"
        echo "7. Используйте Nginx как reverse proxy"
        echo "8. Настройте SSL с Let's Encrypt"
        echo ""
        echo "📖 Подробнее: DEPLOYMENT_GUIDE.md"
        echo ""
        ;;
    5)
        echo "До свидания! 👋"
        exit 0
        ;;
    *)
        echo "❌ Неверный выбор"
        exit 1
        ;;
esac

echo ""
echo "╔═══════════════════════════════════════════════════════════╗"
echo "║          🌐 ПОДКЛЮЧЕНИЕ СОБСТВЕННОГО ДОМЕНА 🌐           ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo ""
echo "1️⃣  КУПИТЕ ДОМЕН:"
echo "   - Namecheap.com (рекомендуется)"
echo "   - GoDaddy.com"
echo "   - Reg.ru (для РФ)"
echo "   - Google Domains"
echo ""
echo "2️⃣  ПОЛУЧИТЕ DNS ДАННЫЕ:"
echo "   - Heroku: heroku domains:add yourdomain.com"
echo "   - DigitalOcean: Используйте IP адрес вашего Droplet'а"
echo "   - PythonAnywhere: Используйте их DNS инструкции"
echo ""
echo "3️⃣  ДОБАВЬТЕ RECORDS В РЕГИСТРАТОР:"
echo "   - A Record или CNAME (в зависимости от хостинга)"
echo ""
echo "4️⃣  ВКЛЮЧИТЕ SSL/HTTPS:"
echo "   - Let's Encrypt (бесплатно!)"
echo "   - Certbot для автоматизации"
echo ""
echo "📖 Полное руководство: DEPLOYMENT_GUIDE.md"
echo "✅ Чек-лист: PRODUCTION_CHECKLIST.md"
echo ""
