name: Deploy to Heroku

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build and push to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      run: |
        docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
        docker build --tag registry.heroku.com/$HEROKU_APP_NAME/web .
        docker push registry.heroku.com/$HEROKU_APP_NAME/web
        heroku container:release web -a $HEROKU_APP_NAME
